apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: {{ .Values.secrets.db.username | b64enc | quote }}
  password: {{ .Values.secrets.db.password | b64enc | quote }}
  host: {{ .Values.secrets.db.host | b64enc | quote }}
  database: {{ .Values.secrets.db.database | b64enc | quote }}
